# Generated by Django 4.2.7 on 2023-11-20 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 0, 10, 31, 621151), editable=False),
        ),
    ]
