# Generated by Django 4.2.7 on 2023-11-20 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exercice_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Author',
        ),
        migrations.AlterField(
            model_name='exercice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 0, 17, 6, 950266), editable=False),
        ),
    ]
