# Generated by Django 4.2.7 on 2023-11-21 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_author_alter_exercice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='resultat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 13, 0, 49, 483160), editable=False),
        ),
    ]
